version: '3'

dotenv: ['.env']

tasks:
  migrateup:
    cmds: 
      - migrate -path db/migration -database $DBSOURCE -verbose up
  migratedown:
    cmds: 
      - migrate -path db/migration -database $DBSOURCE -verbose down
  sqlc:
    cmds:
      - sqlc generate
  test:
    cmds:
      - go test -v -cover ./...
