version: '3'

dotenv: ['.env']

tasks:
  up:
    cmds: 
      - migrate -path db/migration -database $DBSOURCE -verbose up 1
  down:
    cmds: 
      - migrate -path db/migration -database $DBSOURCE -verbose down 1
  sqlc:
    cmds:
      - sqlc generate
  test:
    cmds:
      - go test -v -cover ./...
