// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"github.com/google/uuid"
)

type Access struct {
	ID     uuid.UUID `db:"id" json:"id"`
	System uuid.UUID `db:"system" json:"system"`
	Table  string    `db:"table" json:"table"`
	Type   []string  `db:"type" json:"type"`
}

type Group struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Active bool      `db:"active" json:"active"`
}

type GroupAccess struct {
	GroupID  uuid.UUID `db:"group_id" json:"group_id"`
	AccessID uuid.UUID `db:"access_id" json:"access_id"`
}

type System struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Active bool      `db:"active" json:"active"`
}

type User struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Group  uuid.UUID `db:"group" json:"group"`
	Cpf    string    `db:"cpf" json:"cpf"`
	Name   string    `db:"name" json:"name"`
	Pass   string    `db:"pass" json:"pass"`
	Active bool      `db:"active" json:"active"`
}

type UserAccess struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	AccessID uuid.UUID `db:"access_id" json:"access_id"`
}
