// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Access struct {
	ID     uuid.UUID `db:"id" json:"id"`
	System uuid.UUID `db:"system" json:"system"`
	Table  string    `db:"table" json:"table"`
	Type   []string  `db:"type" json:"type"`
}

type Group struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Active bool      `db:"active" json:"active"`
}

type GroupAccess struct {
	GroupID  uuid.UUID `db:"group_id" json:"group_id"`
	AccessID uuid.UUID `db:"access_id" json:"access_id"`
}

type Session struct {
	ID        uuid.UUID `db:"id" json:"id"`
	User      uuid.UUID `db:"user" json:"user"`
	Token     string    `db:"token" json:"token"`
	Ip        string    `db:"ip" json:"ip"`
	Agent     string    `db:"agent" json:"agent"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

type System struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Tables []string  `db:"tables" json:"tables"`
	Active bool      `db:"active" json:"active"`
}

type User struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Group  uuid.UUID `db:"group" json:"group"`
	Email  string    `db:"email" json:"email"`
	Name   string    `db:"name" json:"name"`
	Pass   string    `db:"pass" json:"pass"`
	Active bool      `db:"active" json:"active"`
}

type UserAccess struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	AccessID uuid.UUID `db:"access_id" json:"access_id"`
}
