// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GroupPermission struct {
	Group      int64 `json:"group"`
	Permission int64 `json:"permission"`
}

type Permission struct {
	ID     int64        `json:"id"`
	Name   string       `json:"name"`
	Create sql.NullBool `json:"create"`
	Read   sql.NullBool `json:"read"`
	Update sql.NullBool `json:"update"`
	Delete sql.NullBool `json:"delete"`
}

type User struct {
	ID     int64  `json:"id"`
	Cpf    string `json:"cpf"`
	Name   string `json:"name"`
	Pass   string `json:"pass"`
	Active bool   `json:"active"`
}

type UserGroup struct {
	User  int64 `json:"user"`
	Group int64 `json:"group"`
}
