// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByCPF(ctx context.Context, cpf string) (User, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPass(ctx context.Context, arg UpdateUserPassParams) (User, error)
}

var _ Querier = (*Queries)(nil)
